apiVersion: v1
data:
  {{ if .Values.secrets.mysql_user }}
  MYSQL_USER: {{  .Values.secrets.mysql_user | b64enc }}
  {{ else }}
  MYSQL_USER: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-mysql-db-user
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
