apiVersion: v1
data:
  {{ if .Values.secrets.mysql_root_password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysql_root_password | b64enc }}
  {{ else }}
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-mysql-root-password
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
