apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-service
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    tier: {{ .Release.Name }}-mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
