apiVersion: v1
data:
  {{ if .Values.secrets.mysql_db_name }}
  MYSQL_DATABASE: {{ .Values.secrets.mysql_db_name | b64enc }}
  {{ else }}
  MYSQL_DATABASE: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-mysql-db-name
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
