apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tier: {{ .Release.Name }}-mysql
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ .Release.Name }}-mysql
spec:
  containers:
  - image: mysql:8.0
    name: mysql-pod
    resources: {}
    env:
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-mysql-db-name
          key: MYSQL_DATABASE
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-mysql-user-password
          key: MYSQL_PASSWORD
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-mysql-root-password
          key: MYSQL_ROOT_PASSWORD
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-mysql-db-user
          key: MYSQL_USER
    {{- with .Values.persistence.pvc.name }}
    volumeMounts:
      - name: data
        mountPath: /var/lib/mysql
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: {{ . }}
    {{- end }}
