apiVersion: v1
data:
  {{ if .Values.secrets.mysql_db_password }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysql_db_password | b64enc }}
  {{ else }}
  MYSQL_PASSWORD: {{ randAlphaNum 20 | b64enc }}
  {{ end }}
kind: Secret
metadata:
  creationTimestamp: null
  name: {{ .Release.Name }}-mysql-user-password
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
